### PR TITLE
Added CatBot and PSR-2

### PR DESCRIPTION
**Pull request by jeroenvdgulik**

### CODE REVIEW

**Comment by skoop** [comment]
@jeroenvdgulik please follow the README. This is only step 1 ;)

**Review by skoop — CHANGES_REQUESTED** [review]
Oh, this is a review. please fix the comment

**Review by ramondelafuente — COMMENTED** [review]
I like the CS fixer addition <3

**Review by skoop — APPROVED** [review]
❤️

**Pull request merged**
